server:
  port: 9991 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  profiles:
    active: dev # 开发环境 dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      
      
      discovery:
        # 服务注册地址
        namespace: public
      config:
        # 配置中心地址
        # 配置文件格式
        file-extension: yml
        namespace: test
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
    gateway:
      routes: # 网关路由配置
        - id: userservice # 路由id，自定义，只要唯一即可
          uri: lb://userservice
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        #          filters: # 过滤器
        #            - AddRequestHeader=Truth, hello world! # 添加请求头
        - id: orderservice # 路由id，自定义，只要唯一即可
          uri: lb://orderservice
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: productservice # 路由id，自定义，只要唯一即可
          uri: lb://productservice
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: addressservice # 路由id，自定义，只要唯一即可
          uri: lb://addressservice
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=1
        - id: cartservice # 路由id，自定义，只要唯一即可
          uri: lb://cartservice
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
      default-filters: # 默认过滤项
        - AddRequestHeader=Truth, hello world lee! # 添加请求头



